To prevent abuse, GMs should be permission restricted (via GM level) …
P0nk/Cosmic pull request #173
Opened 2023-05-12 06:02 UTC by MatthewHinds

…to trade with other non GM players, use their storage (prevent transferring to their other characters), send via Duey and to drop items. GM level is configurable.

2023-05-16 22:52 UTC, MatthewHinds commented
Any thoughts @P0nk ? Or perhaps have I missed something?

2023-05-16 23:05 UTC, JenyaIvanov approved these changes
Good implementation, clean code, good job 👏!

2023-05-17 14:45 UTC, P0nk commented
> Any thoughts @P0nk ? Or perhaps have I missed something?

It looks good, I just haven't had time to test it. Don't worry, I'll get around to it.

2023-05-27 09:50 UTC, P0nk requested changes
Good changes. I have tested them and found some minor issues that I'd like to be fixed before I approve and merge:
- Storage: the error message is shown on exit and on "Arrange item". Should only be on deposit or withdraw item or mesos in my opinion.
- Drop: item drop is restricted, but mesos can still be dropped. Meso drops should also be restricted. This will prevent a GM with level 2 or 3 from using Meso explosion on dropped meso, but we're gonna have to live with that side effect.

2023-05-29 02:32 UTC, MatthewHinds commented
> Good changes. I have tested them and found some minor issues that I'd like to be fixed before I approve and merge:
> 
> - Storage: the error message is shown on exit and on "Arrange item". Should only be on deposit or withdraw item or mesos in my opinion.
> 
> - Drop: item drop is restricted, but mesos can still be dropped. Meso drops should also be restricted. This will prevent a GM with level 2 or 3 from using Meso explosion on dropped meso, but we're gonna have to live with that side effect.

Thanks for the feedback! I've committed new changes to address those two points. Thanks

2023-05-29 13:49 UTC, P0nk approved these changes

2023-05-29 13:50 UTC, merged

2023-06-12 09:24 UTC, ChisBread commented
Maybe missing player shop, hired merchant, wedding gift, cash shop gift etc...