Add Multi-Language Support
P0nk/Cosmic pull request #22
Opened 2021-04-18 21:20 UTC by channarit1994

Server Side's Multi-Language Support

2021-04-19 06:56 UTC, P0nk requested changes
Thanks for the contribution. Commented on some simple style fixes. 

I will do some experimenting on my own to test the parts I found strange, and then get back to you with another verdict.

2021-04-19 06:56 UTC, P0nk commented on src/main/java/tools/data/input/GenericLittleEndianAccessor.java
> +        byte ret[] = new byte[n];
Use `byte[] ret`, not `byte ret[]`

2021-04-19 06:56 UTC, P0nk commented on src/main/java/tools/data/input/GenericLittleEndianAccessor.java
> +            ret[x] = (byte) readByte();
Redundant cast to byte. Remove `(byte)`.

2021-04-19 06:56 UTC, P0nk commented on src/main/java/tools/data/input/GenericLittleEndianAccessor.java
> +            return str;
Inline the String. Do `return new String(ret, CharsetConstants.MapleEncoding);`

2021-04-19 06:56 UTC, P0nk commented on src/main/java/constants/string/CharsetConstants.java
> +    public static Charset MapleEncoding = Charset.forName(MapleLanguageType.LANGUAGE_TH.getAscii()); // Multi-Language Support by MiLin (E.g. TH)
This field is not supposed to change, right? Make it `final`.

2021-04-19 06:56 UTC, P0nk commented on src/main/java/tools/data/output/GenericLittleEndianWriter.java
> +        writeShort((short) s.getBytes().length);
This seems strange to me.

2021-04-19 06:56 UTC, P0nk commented on src/main/java/tools/StringUtil.java
> +		for (int x = in.getBytes().length; x < length; x++) { // Multi-Language Support by MiLin
This seems strange to me.

2021-04-19 06:56 UTC, P0nk commented on src/main/java/tools/StringUtil.java
> +		for (int x = in.getBytes().length; x < length; x++) { // Multi-Language Support by MiLin
This seems strange to me.

2021-04-19 12:55 UTC, channarit1994 commented on src/main/java/constants/string/CharsetConstants.java
> +    public static Charset MapleEncoding = Charset.forName(MapleLanguageType.LANGUAGE_TH.getAscii()); // Multi-Language Support by MiLin (E.g. TH)
I already change it please find a new commit.

2021-04-21 15:31 UTC, P0nk commented
I will put this on hold for a while, and get back to it later. I definitely like the idea, it will just have to wait.

2021-04-21 16:00 UTC, channarit1994 commented
> I will put this on hold for a while, and get back to it later. I definitely like the idea, it will just have to wait.

Thank you

2021-09-08 06:31 UTC, P0nk commented
Implemented in a separate PR: https://github.com/P0nk/Cosmic/pull/51

2021-09-08 06:31 UTC, closed without merging