Complete rework of WhisperHandler including proper chase functionality
P0nk/Cosmic pull request #23
Opened 2021-04-22 20:07 UTC by RubenD96

This PR focuses on WhisperHandler.
Some of the heavenms code was re-used (anti-spam, logging), the rest was all rewritten to be more readable.
Also includes proper chase functionality, admins can use "/c name" to teleport to the player's exact location.
WHISPER packets were redone to have proper flags.

2021-04-23 01:36 UTC, Arnuh commented on src/main/java/net/server/channel/handlers/WhisperHandler.java
> +        if (target != null) {
It's cleaner to just do a null check, give error, and return early. It's used in other places for anti cheat checks so it should be fine for standards.

2021-05-19 17:37 UTC, P0nk requested changes
A lot of noise in the PR due to formatting changes, which made it more difficult to review. 
Did some successful manual tests after fixing the compile issue locally, so it looks good. You just need to fix some minor issues.

2021-05-19 17:37 UTC, P0nk commented on src/main/java/tools/MaplePacketCreator.java
> +                public static final byte RECIEVE = 0x10;
Misspelled "RECEIVE"

2021-05-19 17:37 UTC, P0nk commented on src/main/java/tools/MaplePacketCreator.java
> -        public static byte[] getWhisper(String sender, int channel, String text) {
Can't compile due to this renaming to `getWhisperReceive`. Issue is in method `net.server.world.World#whisper` which uses the old method.

2021-05-19 17:37 UTC, P0nk commented on src/main/java/tools/MaplePacketCreator.java
> +                mplew.writeBool(fromAdmin);
Strange that it worked before without this `writeBool`... (just a comment)

2021-08-19 09:55 UTC, P0nk approved these changes

2021-08-19 09:57 UTC, merged