Fixing bugs, Clean up code, Upgrade to new Syntax
P0nk/Cosmic pull request #89
Opened 2022-08-09 07:52 UTC by truongdatnhan

- Fixing bugs
1.  Character storage won't get initialised when playing for the first time on the server
2. !face command doesn't change player's face
- Clean up
- Upgrade syntax
- Improve readability
- try-with-resource where possible

2022-08-10 10:36 UTC, P0nk commented
I don't see any change to !face command, are you sure you fixed it?

2022-08-10 10:39 UTC, P0nk commented
I don't think the storage fix should be part of character saving, you are mixing two different concerns together.

2022-08-10 18:37 UTC, truongdatnhan commented
I changed by making a double-check for storage after character loading this should be appropriate.
I also pushed some changes on my branch to the master, so you should see change to FaceCommand now.

2022-08-10 21:58 UTC, P0nk requested changes

2022-08-10 21:58 UTC, P0nk commented on src/main/java/client/Character.java
> +
Remove since you have added the fix to character load now?

2022-08-10 21:58 UTC, P0nk commented on src/main/java/net/server/channel/handlers/BBSOperationHandler.java
> +                 * when associated Statement close*/
Agree, but you can remove this comment

2022-08-11 09:09 UTC, truongdatnhan commented
I removed the non-necessary comments. IDK why it won't get updated along with my change through eclipse Git.

2022-08-11 09:15 UTC, P0nk approved these changes

2022-08-11 09:16 UTC, merged